### ISSUE TITLE
Split code into modules

### ISSUE THREAD

**Issue by thetimmorland** [thetimmorland/vex-rt#33]
Currently we export everything from the root vex_rt module. Switching to putting things their own modules may make the docs more readable.

**Comment by thetimmorland** [comment]
Thoughts @nickmertin

**Comment by nickmertin** [comment]
+1 from me. I agree it would make the docs (and in some cases, the code) more readable, and it also seems to be in line with Rust conventions.

**Comment by thetimmorland** [comment]
Ok, It also allows us to write high level module documentation which will appear in the docs.
