### ISSUE TITLE
Reexport libc println!

### ISSUE THREAD

**Issue by thetimmorland** [thetimmorland/vex-rt#34]

**Comment by nickmertin** [comment]
Was this resolved by [this commit](https://github.com/thetimmorland/vex-rt/commit/a6e1ac163ec8f30f831b13e1d5211c31168b293f)?

**Comment by thetimmorland** [comment]
> Was this resolved by [this commit](https://github.com/thetimmorland/vex-rt/commit/a6e1ac163ec8f30f831b13e1d5211c31168b293f)?

Yes
